### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Thor77** [fallenhitokiri/autocomplete-plus-jedi#10]
Requiring `$` from `atom` is no longer supported.
If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead:
  `{$} = require 'atom-space-pen-views'`
  or
  `$ = require 'jquery'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
Or add `"jquery": "^2"` to your package dependencies.

```
Object.Object.defineProperty.get (/usr/share/atom/resources/app/exports/atom.js:43:9)
Object.<anonymous> (/home/jonas/.atom/packages/autocomplete-plus-jedi/lib/jedi-provider.coffee:1:1)
```

**Comment by fallenhitokiri** [comment]
Thanks for the report. I'm currently traveling and don't have much time the next 3 days but I'll try to get to it.

**Comment by fallenhitokiri** [comment]
as discussed here we try to consolidate all jedi providers - therefore this repo will be closed. https://github.com/tinloaf/autocomplete-plus-python-jedi/issues/16
