### ISSUE TITLE
Project.getPath is deprecated.

### ISSUE THREAD

**Issue by Thor77** [fallenhitokiri/autocomplete-plus-jedi#11]
Use ::getPaths instead

```
Project.getPath (/usr/share/atom/resources/app/src/project.js:235:12)
Object.activate (/home/jonas/.atom/packages/autocomplete-plus-jedi/lib/autocomplete-jedi.coffee:10:33)
```

**Comment by fallenhitokiri** [comment]
Thanks for the report. I'm currently traveling and don't have much time the next 3 days but I'll try to get to it.

**Comment by fallenhitokiri** [comment]
as discussed here we try to consolidate all jedi providers - therefore this repo will be closed. https://github.com/tinloaf/autocomplete-plus-python-jedi/issues/16
