### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by cristianpalomino** [fallenhitokiri/autocomplete-plus-jedi#15]
Requiring `$` from `atom` is no longer supported.
If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead:
  `{$} = require 'atom-space-pen-views'`
  or
  `$ = require 'jquery'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
Or add `"jquery": "^2"` to your package dependencies.

```
Object.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app.asar/exports/atom.js:48:11)
Object.<anonymous> (/Users/Gaantz/.atom/packages/autocomplete-plus-jedi/lib/jedi-provider.coffee:1:1)
Object.<anonymous> (/Users/Gaantz/.atom/packages/autocomplete-plus-jedi/lib/jedi-provider.coffee:65:4)
Module._compile (module.js:452:26)
```

**Comment by fallenhitokiri** [comment]
as discussed here we try to consolidate all jedi providers - therefore this repo will be closed. https://github.com/tinloaf/autocomplete-plus-python-jedi/issues/16
