### ISSUE TITLE
Wish: autocomplete for binary libraries

### ISSUE THREAD

**Issue by mostaphaRoudsari** [fallenhitokiri/autocomplete-plus-jedi#19]
Is there any way that the code can be modified to support autocomplete for binary libraries. I tested it for a couple of libraries including clr and it doesn't work.

``` python
import clr
clr.#doesn't show up anything#
```

**Comment by fallenhitokiri** [comment]
This package has be deprecated in favor of https://github.com/tinloaf/autocomplete-plus-python-jedi

If you still feel like getting it to work you should check the Python script / jedi, which is in charge of providing the completion suggestions.

**Comment by mostaphaRoudsari** [comment]
Thanks!
